---
title: "Case Study"
author: "Linze Yu"
date: "`r Sys.Date()`"
output:
  rmdformats::downcute:
    self_contained: TRUE
    default_style: "light"
    downcute_theme: "default"
    fig_width: 7
    fig_height: 5
    use_bookdown: TRUE
    gallery: TRUE
    lightbox: TRUE
    highlight: tango
editor_options: 
  markdown: 
    wrap: 72
---

```{r, 代码全局设置, echo = F}
knitr::opts_chunk$set(warning = F, error = F, message = F, prompt = F, comment = "", echo = T, dpi = 200, collapse = F, fig.align = "left", dev = "png", cache = T)
# , eval = F代码显示不运行
# , include = F代码运行, 不显示代码和结果
# , echo = T 显示代码块
# , prompt = T使用>开始代码
# , comment = ""结果不使用##
# , collapse = T#代码合并结果
# , out.width/out.height = 0.8缩放
# , fig.align = "left","center","right"对齐方式
# , dev = "pdf","png","svg","jpeg"记录设备
# , cache = T
```

## 加载包
```{r 加载包}
library("linr") #
library("ggbeeswarm") # 散点防止重合
library("ggExtra") # 边际直方图/密度曲线*
library("ggside") # 边际直方图/密度曲线
# library("ggwordcloud") # 词云
# library("gghalves") # 组合
showtext_auto()
showtext_opts(dpi = 400) # 默认(大约为dpi = dpi*2)
```

# Case 1
```{r}
import("D:/desktop/book/tidybook/data/paper/Environmental factors shaping the gut microbiome in a Dutch population.csv") -> data
head(data)
```

```{r}
data$RELATIONSHIP.0 <- factor(data$RELATIONSHIP.0, levels = c("PAR_CH", "PARTNERS", "RND.PAIR", "SIBL"))
```

```{r, fig.width = 7, fig.height = 5}
data %>%
  ggplot(aes(x = RELATIONSHIP.0, y = BC_Spec, color = RELATIONSHIP.0)) +
  geom_violin(alpha = 0.4, width = 0.8, position = position_dodge(width = 0.8), size = 0.75) +
  geom_boxplot(alpha = 0.2, width = 0.4, position = position_dodge(width = 0.8), size = 0.75, outlier.colour = NA) +
  geom_jitter(alpha = 0.2, position = position_jitterdodge(jitter.width = 1, jitter.height = 0, dodge.width = 0.8)) +
  scale_color_manual(values = cols) +
  scale_fill_manual(values = fills) +
  lin_theme +
  theme(legend.position = "none", text = element_text(size = 16)) +
  labs(y = "Bray-Curtis distance of Species")
```

# Case 2
```{r}
library("vegan")
inMBss <- read.table("D:/desktop/book/tidybook/data/paper/inMBss.tsv", row.names = 1, header = T)
dim(inMBss)
distMatrix <- vegdist(inMBss, method = "bray")
pCoa <- cmdscale(distMatrix, eig = T, k = 2)
```

```{r}
varExp <- (eigenvals(pCoa) / sum(eigenvals(pCoa)))[1:2]
xVar <- as.numeric(varExp[1] * 100)
yVar <- as.numeric(varExp[2] * 100)
```

```{r}
pCoaVecs <- as.data.frame(pCoa$points)
colnames(pCoaVecs) <- paste0("PCo", c(1:2))
pCoaVecs$ID <- row.names(pCoaVecs)

inMBssID <- inMBss
inMBssID$ID <- row.names(inMBssID)
inMBssPrev <- inMBssID[, c("ID", "k__Bacteria.p__Bacteroidetes.c__Bacteroidia.o__Bacteroidales.f__Prevotellaceae.g__Prevotella.s__Prevotella_copri")]
colnames(inMBssPrev) <- c("ID", "P.copri")
pCoaVecsTaxa <- merge(pCoaVecs, inMBssPrev, by = "ID")
```

```{r}
pCoaVecsTaxa %>%
  ggplot(aes(x = PCo1, y = PCo2, color = P.copri, fill = P.copri)) +
  geom_point(size = 2, shape = 21, alpha = 0.5) +
  scale_color_gradientn(colours = viridis::viridis(1000)) +
  scale_fill_gradientn(colours = viridis::viridis(1000)) +
  labs(x = "PCo1 25.62%", y = "PCo2 10.81%") +
  lin_theme +
  theme(text = element_text(size = 16))
```


[1]GACESA R, KURILSHIKOV A, VICH VILA A, et al. Environmental factors shaping the gut microbiome in a Dutch population [J]. **Nature**, 2022, 604(7907): 732-9.  
  
(IF: 49.962)  
  
[2]丁惠国,屠红,曲春枫,等.原发性肝癌的分层筛查与监测指南(2020版) [Z].临床肝胆病杂志.2021:286-95  






# Case 1(prism1.xlsx)
```{r, fig.width = 7, fig.height = 5}
import("D:/desktop/book/tidybook/data/paper/prism1.xlsx") %>%
  longer_dt(name = "group", value = "value") %>%
  summarize_dt(n = .N, sd = sd(value), mean = mean(value), by = group) %>%
  ggplot(aes(x = group, y = mean)) +
  geom_errorbar(aes(ymin = mean - sd / sqrt(n), ymax = mean + sd / sqrt(n)), color = 1, width = 0.25, size = 1, lineend = "square") +
  geom_col(color = NA, fill = "#95AAD3", alpha = 1, width = 0.5, size = 1, lineend = "square") +
  expand_limits(y = c(0, 14)) +
  scale_y_continuous(breaks = seq(0, 50, by = 2), minor_breaks = seq(0, 50, by = 1)) +
  labs(x = "", y = "N-cadherin relative expression(fold)", tag = "A") +
  lin_theme
```

```{r, eval = F}
theme(
  axis.title.y = element_text(size = 15, vjust = 0.5, hjust = 0.5, angle = 90, margin = margin(0, 3, 0, 0)),
  axis.text.x = element_text(vjust = 1, hjust = 1, angle = 45, margin = margin(1, 0, 0, 0)),
  panel.background = element_rect(color = NA, fill = NA),
  legend.background = element_rect(color = NA, fill = NA),
  legend.key = element_rect(color = NA, fill = NA),
  axis.line = element_line(color = "#96999C", size = 1, lineend = "square"),
  axis.ticks = element_line(color = "#96999C", size = 1),
  axis.ticks.length = unit(0.15, "cm"),
) -> theme
```

# Case 2(prism2.xlsx)
```{r, fig.width = 7, fig.height = 5}
# col <- c("#BD3645", "#696AAD")
import("D:/desktop/book/tidybook/data/paper/prism2.xlsx") %>%
  longer_dt(group1, name = "group", value = "value") -> c
c[, c("mean", "sd", "n") := .(mean(value), sd(value), .N), by = c("group", "group1")]
c[, -c("value")] %>%
  distinct_dt() %>%
  ggplot(aes(x = group, y = mean, fill = group1)) +
  geom_errorbar(aes(ymin = mean - sd / sqrt(n), ymax = mean + sd / sqrt(n)), color = 1, width = 0.325, size = 1, lineend = "square", position = position_dodge(width = 0.65)) +
  geom_col(color = NA, alpha = 1, width = 0.65, size = 1, lineend = "square", position = position_dodge2(width = 1.3)) +
  scale_fill_manual(values = cols) +
  scale_y_continuous(breaks = seq(0, 50, by = 2), minor_breaks = seq(0, 50, by = 1)) +
  labs(x = "", y = "Relative luciferase activity(fold)", tag = "B") +
  lin_theme +
  theme(legend.position = (c(0.2, 1)))
```

```{r, eval = F}
theme(
  axis.title.y = element_text(size = 15, vjust = 0.5, hjust = 0.5, angle = 90, margin = margin(0, 3, 0, 0)),
  axis.text.x = element_text(vjust = 1, hjust = 1, angle = 45, margin = margin(1, 0, 0, 0)),
  panel.background = element_rect(color = NA, fill = NA),
  legend.background = element_rect(color = NA, fill = NA),
  legend.key = element_rect(color = NA, fill = NA),
  axis.line = element_line(color = "#96999C", size = 1, lineend = "square"),
  axis.ticks = element_line(color = "#96999C", size = 1),
  axis.ticks.length = unit(0.15, "cm"),
  legend.position = (c(0.15, 0.9))
) -> theme
```

# Case 3(prism3.xlsx)
```{r, fig.width = 5, fig.height = 5}
import("D:/desktop/book/tidybook/data/paper/prism3.xlsx") %>%
  longer_dt(n, name = "group", value = "value") %>%
  ggplot(aes(x = group, y = value)) +
  geom_line(aes(group = n), alpha = 1, linetype = 1, color = "#96999C", lineend = "square") +
  expand_limits(y = c(0, 20)) +
  geom_point(shape = 21, size = 3, color = 1, fill = 1) +
  labs(x = "", y = "Relative miR-776-3p expression", title = "n=25 p<0.001") +
  lin_theme
```

```{r, eval = F}
theme(
  axis.title.y = element_text(size = 15, vjust = 0.5, hjust = 0.5, angle = 90, margin = margin(0, 3, 0, 0)),
  axis.text.x = element_text(vjust = 1, hjust = 1, angle = 45, margin = margin(1, 0, 0, 0)),
  panel.background = element_rect(color = NA, fill = NA),
  legend.background = element_rect(color = NA, fill = NA),
  legend.key = element_rect(color = NA, fill = NA),
  axis.line = element_line(color = 1, size = 0.5, lineend = "square"),
  axis.ticks = element_line(color = 1, size = 0.5),
  axis.ticks.length = unit(0.15, "cm"),
  plot.title = element_text(size = 15, hjust = 0.5, angle = 0, lineheight = 1, margin = margin(0, 1, 0, 0))
) -> theme
```

# Case 4
## 散点图
```{r}
import("D:/desktop/book/tidybook/data/case_1/0.xlsx") %>%
  ggplot(aes(x = Adjacent, y = Tumor)) +
  geom_point(shape = 21, alpha = 0.5, color = "#696AAD", fill = "#95AAD3", stroke = 1, size = 5) +
  scale_x_continuous(breaks = seq(0, 20, by = 1), minor_breaks = seq(0, 0, by = 0)) +
  scale_y_continuous(breaks = seq(0, 20, by = 4), minor_breaks = seq(0, 0, by = 0)) +
  expand_limits(x = c(2, 6), y = c(0, 14)) +
  coord_fixed(ratio = 1 / 4) +
  lin_theme +
  labs(x = "Adjacent", y = "Tumor")
```

## 折线图
```{r}
import("D:/desktop/book/tidybook/data/case_1/1.xlsx") %>%
  longer_dt(Day, name = "group", value = "value") -> c
c[, c("mean", "sd", "n") := .(mean(value), sd(value), .N), by = c("group", "Day")]
c[, -c("value")] %>%
  distinct_dt() %>%
  ggplot(aes(x = Day, y = mean, color = group, fill = group)) +
  geom_point(size = 2, shape = 21, alpha = 0.5, stroke = 1, fill = NA) +
  geom_errorbar(aes(ymin = mean - sd / sqrt(n), ymax = mean + sd / sqrt(n)), size = 0.5, width = 0.3, lineend = "square") +
  geom_line(size = 0.5, lineend = "square") +
  scale_x_continuous(breaks = seq(0, 20, by = 1), minor_breaks = seq(0, 0, by = 0)) +
  scale_y_continuous(breaks = seq(0, 1200, by = 100), minor_breaks = seq(0, 0, by = 0)) +
  scale_color_manual(values = cols) +
  scale_fill_manual(values = fills) +
  coord_fixed(ratio = 2 / 200) +
  lin_theme +
  theme(legend.position = (c(0.4, 0.95))) +
  labs(x = "Day(s)", y = "Values")
```

## 柱状图1
```{r}
import("D:/desktop/book/tidybook/data/case_1/2.xlsx") %>%
  longer_dt(Replicates, name = "group", value = "value") %>%
  summarize_dt(n = .N, sd = sd(value), mean = mean(value), by = group) %>%
  ggplot(aes(x = group, y = mean, color = group, fill = group)) +
  geom_errorbar(aes(ymin = mean - sd / sqrt(n), ymax = mean + sd / sqrt(n)), width = 0.25, alpha = 1, size = 1, lineend = "square") +
  geom_col(width = 0.5, alpha = 0.5, size = 1, lineend = "square") +
  scale_color_manual(values = cols) +
  scale_fill_manual(values = fills) +
  lin_theme +
  theme(legend.position = "none") +
  labs(x = "", y = "Values")
```

## 柱状图2
```{r}
import("D:/desktop/book/tidybook/data/case_1/3.xlsx") %>%
  longer_dt(Replicates, name = "group", value = "value") %>%
  summarize_dt(n = .N, sd = sd(value), mean = mean(value), by = group) %>%
  ggplot(aes(x = group, y = mean, color = group, fill = group)) +
  geom_errorbar(aes(ymin = mean - sd / sqrt(n), ymax = mean + sd / sqrt(n)), width = 0.25, alpha = 1, size = 1, lineend = "square") +
  geom_col(width = 0.5, alpha = 0.5, size = 1, lineend = "square") +
  scale_color_manual(values = cols) +
  scale_fill_manual(values = fills) +
  scale_y_break(c(10, 100), scales = 0.25) +
  lin_theme +
  theme(legend.position = "none") +
  labs(x = "", y = "Values")
```

## 对比柱状图
```{r}
import("D:/desktop/book/tidybook/data/case_1/4.xlsx") %>%
  longer_dt(name = "group", value = "value") -> c
c[, c("mean", "sd", "n") := .(mean(value), sd(value), .N), by = c("group", "group1")]
c[, -c("value")] %>%
  distinct_dt() %>%
  ggplot(aes(x = group, y = mean, color = group1, fill = group1)) +
  geom_errorbar(aes(ymin = mean - sd / sqrt(n), ymax = mean + sd / sqrt(n)), size = 1, width = 0.3, lineend = "square", position = position_dodge(width = 1)) +
  geom_col(width = 0.5, alpha = 0.5, position = position_dodge(width = 1), size = 1, lineend = "square") +
  scale_y_continuous(breaks = seq(0, 1500, by = 200), minor_breaks = seq(0, 0, by = 0)) +
  scale_color_manual(values = cols) +
  scale_fill_manual(values = fills) +
  lin_theme +
  theme(legend.position = (c(0.9, 0.9))) +
  labs(x = "", y = "Values")
```

## 生存曲线
```{r}
F <- import("D:/desktop/book/tidybook/data/case_1/5.xlsx")
fit <- survfit(Surv(Time_Months, Status) ~ Expression, data = F)
fit
p <- ggsurvplot(fit,
  data = F,
  fun = NULL,
  linetype = 1,
  conf.int = FALSE,
  pval = FALSE,
  pval.method = FALSE,
  test.for.trend = FALSE,
  surv.median.line = "hv",
  risk.table = FALSE,
  cumevents = FALSE,
  cumcensor = FALSE,
  tables.height = 0.25,
  legend = c(0.95, 0.95), # 指定图例位置
  facet.by = NULL,
  font.family = "Source Han Sans",
  ggtheme = lin_theme,
  add.all = FALSE,
  combine = FALSE
) +
  labs(x = "Time(Months)", y = "Cumsurvival(%)")
p
```

## 热图
```{r}
import("D:/desktop/book/tidybook/data/case_1/6.xlsx") %>%
  mutate_vars(2:3, scale) %>%
  longer_dt(ID, name = "group", value = "value") %>%
  ggplot(aes(x = ID, y = group)) +
  geom_tile(alpha = 1, aes(fill = value)) +
  scale_fill_gradient(low = "#F8CDCD", high = "#696AAD") +
  expand_limits(x = c(1, 20), fill = seq(-2, 2, by = 1)) +
  scale_x_continuous(breaks = seq(1, 20, by = 2), minor_breaks = seq(0, 0, by = 0)) +
  lin_theme
```

# Case 5
## 散点图
```{r}
import("D:/desktop/book/tidybook/data/case_2/0.xlsx") %>%
  ggplot(aes(x = X, y = Y)) +
  geom_point(size = 5, shape = 21, alpha = 0.5, color = "#696AAD", fill = "#95AAD3", stroke = 1) +
  coord_fixed(ratio = 1 / 1) +
  lin_theme
```

## 折线图
```{r}
import("D:/desktop/book/tidybook/data/case_2/1.xlsx") %>%
  longer_dt(Day, name = "group", value = "value") -> c
c[, c("mean", "sd", "n") := .(mean(value), sd(value), .N), by = c("group", "Day")]
c[, -c("value")] %>%
  distinct_dt() %>%
  ggplot(aes(Day, mean, color = group, fill = group)) +
  geom_point(size = 2, shape = 21, alpha = 0.5, stroke = 1, fill = NA, position = position_dodge(0.2)) +
  geom_errorbar(aes(ymin = mean - sd / sqrt(n), ymax = mean + sd / sqrt(n)), size = 0.7, width = 0.2, lineend = "square", position = position_dodge(0.2)) +
  geom_line(size = 1, lineend = "square", position = position_dodge(0.2)) +
  scale_color_manual(values = cols) +
  scale_fill_manual(values = fills) +
  coord_fixed(ratio = 1 / 1) +
  lin_theme +
  theme(legend.position = (c(0.35, 0.95)))
```

## 柱状图1
```{r}
import("D:/desktop/book/tidybook/data/case_2/2.xlsx") %>%
  longer_dt(name = "group", value = "value") %>%
  summarize_dt(n = .N, sd = sd(value), mean = mean(value), by = group) %>%
  ggplot(aes(x = reorder(group, -mean), y = mean, color = group, fill = group)) +
  geom_errorbar(aes(ymin = mean - sd / sqrt(n), ymax = mean + sd / sqrt(n)), width = 0.25, alpha = 1, size = 1, lineend = "square") +
  geom_col(width = 0.5, alpha = 0.5, size = 1, lineend = "square") +
  scale_y_continuous(breaks = seq(0, 2, by = 0.5), minor_breaks = seq(0, 0, by = 0)) +
  lin_theme +
  scale_color_manual(values = cols) +
  scale_fill_manual(values = fills) +
  theme(legend.position = ("none"))
```

## 对比柱状图
```{r}
import("D:/desktop/book/tidybook/data/case_2/3.xlsx") %>%
  longer_dt(name = "group", value = "value") -> c
c[, c("mean", "sd", "n") := .(mean(value), sd(value), .N), by = c("group", "group1")]
c[, -c("value")] %>%
  distinct_dt() %>%
  ggplot(aes(x = group, y = mean, color = group1, fill = group1)) +
  geom_errorbar(aes(ymin = mean - sd / sqrt(n), ymax = mean + sd / sqrt(n)), size = 1, width = 0.3, lineend = "square", position = position_dodge(width = 1)) +
  geom_col(width = 0.5, alpha = 0.5, position = position_dodge(width = 1), size = 1, lineend = "square") +
  scale_y_continuous(breaks = seq(0, 5, by = 1), minor_breaks = seq(0, 0, by = 0)) +
  scale_color_manual(values = cols) +
  scale_fill_manual(values = fills) +
  lin_theme +
  theme(legend.position = (c(0.95, 0.95)))
```

## 箱线图
```{r}
import("D:/desktop/book/tidybook/data/case_2/4.xlsx") %>%
  longer_dt(name = "group", value = "value") %>%
  ggplot(aes(group, value, color = group, fill = group)) +
  geom_half_boxplot(alpha = 0.3, size = 0.618, position = position_nudge(x = 0, y = 0), side = "l", lineend = "square") +
  geom_half_violin(alpha = 0.3, size = 0.618, position = position_nudge(x = 0, y = 0), side = "r", trim = FALSE, lineend = "square") +
  scale_y_continuous(breaks = seq(-5, 5, by = 1), minor_breaks = seq(0, 0, by = 0)) +
  scale_color_manual(values = cols) +
  scale_fill_manual(values = fills) +
  lin_theme +
  theme(legend.position = ("none"))
```

## 生存曲线
```{r}
F <- import("D:/desktop/book/tidybook/data/case_2/5.xlsx")
fit <- survfit(Surv(Time_Months, Status) ~ Expression, data = F)
p <- ggsurvplot(fit, data = F, fun = NULL, linetype = 1, conf.int = FALSE, pval = FALSE, pval.method = FALSE, test.for.trend = FALSE, surv.median.line = "none", risk.table = FALSE, cumevents = FALSE, cumcensor = FALSE, tables.height = 0.25, facet.by = NULL, add.all = FALSE, combine = FALSE)
p
```

## 柱状图2
```{r}
import("D:/desktop/book/tidybook/data/case_2/6.xlsx") %>%
  longer_dt(name = "group", value = "value") %>%
  summarize_dt(n = .N, sd = sd(value), mean = mean(value), by = group) %>%
  ggplot(aes(group, mean, color = group, fill = group)) +
  geom_errorbar(aes(ymin = mean - sd / sqrt(n), ymax = mean + sd / sqrt(n)), width = 0.25, alpha = 1, size = 1, lineend = "square") +
  geom_col(width = 0.8, alpha = 0.5, size = 1, lineend = "square") +
  scale_color_manual(values = cols) +
  scale_fill_manual(values = fills) +
  lin_theme +
  theme(legend.position = ("none"))
```

## 热图
```{r}
import("D:/desktop/book/tidybook/data/case_2/7.xlsx") %>%
  mutate_vars(2:3, scale) %>%
  longer_dt(ID, name = "Group", value = "value") %>%
  ggplot(aes(x = ID, y = Group)) +
  geom_tile(alpha = 1, aes(fill = value)) +
  scale_fill_gradient(low = "#F8CDCD", high = "#696AAD") +
  expand_limits(x = c(1, 12), fill = seq(-2, 2, by = 1)) +
  scale_x_continuous(breaks = seq(1, 20, by = 2), minor_breaks = seq(0, 0, by = 0)) +
  lin_theme
```

# 平均值的标准误(小提琴.xlsx)
```{r, echo = F}
import("D:/desktop/book/tidybook/data/other/小提琴.xlsx") %>%
  longer_dt(name = "group", value = "value") -> c
c[, c("mean", "sd", "n") := .(mean(value), sd(value), .N), by = group]
c %>%
  ggplot(aes(x = group, y = mean)) +
  geom_violin(aes(x = group, y = value), color = NA, fill = "#696AAD", alpha = 0.3, width = 0.5) +
  geom_errorbar(aes(ymin = mean - sd / sqrt(n), ymax = mean + sd / sqrt(n)), color = "#696AAD", width = 0.2, size = 1) +
  geom_segment(x = 1, y = 1.871, xend = 2, yend = 2.852, color = "#696AAD", size = 1) +
  geom_segment(x = 2, y = 2.852, xend = 3, yend = 3.180, color = "#696AAD", size = 1) +
  geom_segment(x = 3, y = 3.180, xend = 4, yend = 2.913, color = "#696AAD", size = 1) +
  geom_point(aes(x = group, y = mean), color = "#696AAD", shape = 21, size = 2, fill = NA, stroke = 1, ) +
  scale_y_continuous(name = "value", breaks = seq(0, 5, by = 1), minor_breaks = seq(0, 0, by = 0)) +
  scale_x_discrete(name = "", limits = c("1", "2", "3", "4"), labels = c("A", "B", "C", "D"), breaks = c("1", "2", "3", "4")) +
  lin_theme
```
