---
title: "基础部分"
author: "Linze Yu"
date: "`r Sys.Date()`"
output:
  rmdformats::downcute:
    self_contained: TRUE
    default_style: "light"
    downcute_theme: "default"
    fig_width: 7
    fig_height: 5
    use_bookdown: TRUE
    gallery: TRUE
    lightbox: TRUE
    highlight: tango
editor_options: 
  markdown: 
    wrap: 72
---

```{r, 代码全局设置, echo = F}
knitr::opts_chunk$set(warning = F, error = F, message = F, prompt = F, comment = "", echo = T, dpi = 1200, collapse = F, fig.align = "left", dev = "png", cache = T)
# , eval = F代码显示不运行
# , include = F代码运行, 不显示代码和结果
# , echo = T 显示代码块
# , prompt = T使用>开始代码
# , comment = ""结果不使用##
# , collapse = T#代码合并结果
# , out.width/out.height = 0.8缩放
# , fig.align = "left","center","right"对齐方式
# , dev = "pdf","png","svg","jpeg"记录设备
# , cache = T
```

<font size = 6>**数据导入** > **数据清洗** > **数据变换** > **数据可视化** > 数据建模 > **可重现与交互报告**</font>

```{r}
names(knitr::knit_engines$get())
```

## 加载包
```{r 加载包}
library("YuriR") #
library("ggbeeswarm") # 散点防止重合
library("tayloRswift") #
library("ggside") # 边际直方图/密度曲线
# library("ggwordcloud")#词云
# library("gghalves")#组合
# library("rio")#
# library("tidyverse")#
# library("tidyfst")#
# library("data.table")#
# library("knitr")#
# library("kableExtra")#表格+
# ----------------------------------------------
# install.packages("devtools")
# devtools::install_github("r-lib/devtools")
# devtools::install_github("Yurisuriyel/YuriR")
# font_install(source_han_serif())
font_families()
```

# RMarkdown使用
## RMarkdown
```{r,eval = F}
devtools::install_github("rstudio/rmarkdown")
```

## tinytex(PDF)
```{r,eval = F}
install.packages("tinytex")
tinytex::install_tinytex()
```

## knitr
```{r,eval = F}
install.packages("knitr")
```

## [主题选择网站](https://bootswatch.com/3/)
  
# Intel®Math Kernel Library

## D:/R-4.1.3/bin/x64

## 测试*2
```{r}
m <- 10000
n <- 2000
a <- matrix(runif(m * n), m, n)
system.time(s <- svd(a, nu = 0, nv = 0))
```

# 多线程
```{r}
plan(workers = 16)
```

# 升级R版本
```{r,eval = F}
install.packages("installr")
installr::updateR(fast = T, copy_packages = T)
```

# 整理代码
**(styler)**
```{r, eval = F}
styler:::style_active_file()
```
Addins %>% style active file

```{r}
seq(-3, 3, by = 0.01) %>%
  expand.grid(x = ., y = .) %>%
  ggplot(aes(x = (1 - x - sin(y^2)), y = (1 + y - cos(x^2)))) +
  geom_point(alpha = 0.05, shape = 20, size = 0) +
  Yuri_theme +
  coord_polar()
```

```{r, eval = F}
seq(-10, 10, by = 0.05) %>%
  expand.grid(x = ., y = .) %>%
  ggplot(aes(x = (x + pi * sin(y)), y = (y + pi * sin(x)))) +
  geom_point(alpha = 0.1, shape = 15, size = 1, col = "darkmagenta") +
  Yuri_theme
```

```{r}
t <- seq(0, 100 * pi, length.out = 500 * 100)
data.frame(x = t^(1 / 2) * cos(t), y = t^(1 / 2) * sin(t)) %>%
  rbind(-.) %>%
  ggplot(aes(x, y)) +
  geom_polygon() +
  Yuri_theme
```
